quarkus.neo4j.pool.metrics.enabled = true

# Disabling SSL is not recommended in production and only needed for this integration test.
# Disabling SSL will disable encrypted bolt communication.
quarkus.ssl.native=false
